//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALearningSystemWebAndLoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class NavigationToCategoryHierachyPageCoded : WebTest
    {

        public NavigationToCategoryHierachyPageCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://stage.telerikacademy.com/");
            request1.ThinkTime = 1;
            WebTestRequest request1Dependent1 = new WebTestRequest("http://stage.telerikacademy.com/fonts/glyphicons-halflings-regular.eot");
            request1Dependent1.ThinkTime = 1;
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/"));
            request1Dependent1.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent1);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://stage.telerikacademy.com/");
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/"));
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://stage.telerikacademy.com/Users/Auth/Login");
            request3.ThinkTime = 1;
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/"));
            WebTestRequest request3Dependent1 = new WebTestRequest("http://stage.telerikacademy.com/fonts/glyphicons-halflings-regular.eot");
            request3Dependent1.ThinkTime = 15;
            request3Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/Users/Auth/Login"));
            request3Dependent1.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent1);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://stage.telerikacademy.com/Users/Auth/Login");
            request4.Method = "POST";
            request4.ExpectedResponseUrl = "http://stage.telerikacademy.com/";
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/Users/Auth/Login"));
            FormPostHttpBody request4Body = new FormPostHttpBody();
            request4Body.FormPostParameters.Add("UsernameOrEmail", "GiantTestUser");
            request4Body.FormPostParameters.Add("Password", "123456");
            request4.Body = request4Body;
            WebTestRequest request4Dependent1 = new WebTestRequest("http://stage.telerikacademy.com/fonts/glyphicons-halflings-regular.eot");
            request4Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/"));
            request4Dependent1.QueryStringParameters.Add("", "", false, false);
            request4.DependentRequests.Add(request4Dependent1);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://stage.telerikacademy.com/Administration/Navigation");
            request5.ThinkTime = 1;
            request5.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/"));
            WebTestRequest request5Dependent1 = new WebTestRequest("http://stage.telerikacademy.com/fonts/glyphicons-halflings-regular.eot");
            request5Dependent1.ThinkTime = 3;
            request5Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/Administration/Navigation"));
            request5Dependent1.QueryStringParameters.Add("", "", false, false);
            request5.DependentRequests.Add(request5Dependent1);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://stage.telerikacademy.com/Administration_Courses/CourseInstanceCategoriesHi" +
                    "erarchy");
            request6.ThinkTime = 1;
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/Administration/Navigation"));
            WebTestRequest request6Dependent1 = new WebTestRequest("http://stage.telerikacademy.com/fonts/glyphicons-halflings-regular.eot");
            request6Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/Administration_Courses/CourseInstanceCategoriesHi" +
                        "erarchy"));
            request6Dependent1.QueryStringParameters.Add("", "", false, false);
            request6.DependentRequests.Add(request6Dependent1);
            WebTestRequest request6Dependent2 = new WebTestRequest("http://stage.telerikacademy.com/Administration_Courses/CourseInstanceCategoriesHi" +
                    "erarchy/ReadCategories");
            request6Dependent2.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request6Dependent2.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request6Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://stage.telerikacademy.com/Administration_Courses/CourseInstanceCategoriesHi" +
                        "erarchy"));
            request6.DependentRequests.Add(request6Dependent2);
            yield return request6;
            request6 = null;
        }
    }
}
